### ISSUE TITLE
start后进不去server，log显示有报错

### ISSUE THREAD

**Issue by yuyun2000** [arkohut/pensieve#18]
serve.log最后的输出如下：
```
| |                     'print_verbose': False,                             | |
| |                     'text_score': 0.5,                                  | |
| |                     'use_cls': True,                                    | |
| |                     'use_det': True,                                    | |
| |                     'use_rec': True,                                    | |
| |                     'use_space_char': True,                             | |
| |                     'width_height_ratio': 40                            | |
| |                 }                                                       | |
| |        kwargs = {}                                                      | |
| |          self = <rapidocr_openvino.main.RapidOCR object at              | |
| |                 0x00000127C4291840>                                     | |
| +-------------------------------------------------------------------------+ |
+-----------------------------------------------------------------------------+
KeyError: 'max_side_len'
```

watch.log报错如下：
```
Failed to retrieve libraries: 502 - 
```

**Comment by yuyun2000** [comment]
更新0.19后，好像可以进行ocr识别了，但是embedding我已经设置了从modelscope下载，为啥日志里还是有huggingface的下载失败记录

**Comment by arkohut** [comment]
修改配置后需要 `memos stop && memos start` 重启一下才生效～

**Comment by yuyun2000** [comment]
现在依旧进不去ui界面，但是不是前面的连不上，而是空白界面

**Comment by yuyun2000** [comment]
而且我确定了，就算我 use_modelscope: true 他还是会不断尝试从hug下载，导致log信息很多

**Comment by arkohut** [comment]
发个报错信息看看？

**Comment by yuyun2000** [comment]
watch.log报错如下：

Failed to retrieve libraries: 502 -  
始终只有这一行
serve的信息如下：
```
2024-11-20 12:12:33,373 - ERROR - Error updating indexes for entity 258: [WinError 4392] 在重分析点缓冲区中的数据无效。: '..\\..\\blobs\\823d01be739976929f1de49c19ba4eec80e604cf' -> 'C:\\Users\\Administrator\\.cache\\huggingface\\hub\\models--jinaai--jina-bert-implementation\\snapshots\\f3ec4cf7de7e561007f27c9efc7148b0bd713f81\\configuration_bert.py'
2024-11-20 12:12:33,375 - INFO - 127.0.0.1:6625 - "POST /libraries/1/entities?update_index=true HTTP/1.1" 500
2024-11-20 12:12:33,375 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\memos\server.py", line 227, in new_entity
    crud.update_entity_index(entity, db)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\memos\crud.py", line 755, in update_entity_index
    embeddings = get_embeddings([vec_metadata])
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\memos\embedding.py", line 63, in get_embeddings
    embeddings = generate_embeddings(texts)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\memos\embedding.py", line 45, in generate_embeddings
    init_embedding_model()
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\memos\embedding.py", line 36, in init_embedding_model
    model = SentenceTransformer(model_dir, trust_remote_code=True)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 308, in __init__
    modules, self.module_kwargs = self._load_sbert_model(
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 1728, in _load_sbert_model
    module = module_class(model_name_or_path, cache_dir=cache_folder, backend=self.backend, **kwargs)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\sentence_transformers\models\Transformer.py", line 77, in __init__
    config = self._load_config(model_name_or_path, cache_dir, backend, config_args)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\sentence_transformers\models\Transformer.py", line 128, in _load_config
    return AutoConfig.from_pretrained(model_name_or_path, **config_args, cache_dir=cache_dir)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1026, in from_pretrained
    config_class = get_class_from_dynamic_module(
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\transformers\dynamic_module_utils.py", line 540, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\transformers\dynamic_module_utils.py", line 344, in get_cached_module_file
    resolved_module_file = cached_file(
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\transformers\utils\hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\huggingface_hub\file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\huggingface_hub\file_download.py", line 994, in _hf_hub_download_to_cache_dir
    _create_symlink(blob_path, pointer_path, new_blob=False)
  File "C:\ProgramData\anaconda3\envs\tor2\lib\site-packages\huggingface_hub\file_download.py", line 586, in _create_symlink
    os.symlink(src_rel_or_abs, abs_dst)
OSError: [WinError 4392] 在重分析点缓冲区中的数据无效。: '..\\..\\blobs\\823d01be739976929f1de49c19ba4eec80e604cf' -> 'C:\\Users\\Administrator\\.cache\\huggingface\\hub\\models--jinaai--jina-bert-implementation\\snapshots\\f3ec4cf7de7e561007f27c9efc7148b0bd713f81\\configuration_bert.py'
2024-11-20 12:12:34,346 - INFO - 127.0.0.1:6651 - "GET /libraries/1/folders/1/entities?limit=100&offset=0 HTTP/1.1" 200
2024-11-20 12:12:35,202 - INFO - 127.0.0.1:6657 - "GET /libraries/1/folders/1/entities?limit=100&offset=100 HTTP/1.1" 200
2024-11-20 12:12:36,017 - INFO - 127.0.0.1:6659 - "GET /libraries/1/folders/1/entities?limit=100&offset=200 HTTP/1.1" 200
2024-11-20 12:12:36,786 - INFO - 127.0.0.1:6665 - "GET /libraries/1/folders/1/entities?limit=100&offset=300 HTTP/1.1" 200
2024-11-20 12:14:49,644 - INFO - 127.0.0.1:7086 - "GET / HTTP/1.1" 200
2024-11-20 12:14:49,663 - INFO - 127.0.0.1:7086 - "GET /_app/immutable/entry/start.4362bce6.js HTTP/1.1" 304
2024-11-20 12:14:49,672 - INFO - 127.0.0.1:7086 - "GET /_app/immutable/chunks/scheduler.5c1cff6e.js HTTP/1.1" 304
2024-11-20 12:14:49,675 - INFO - 127.0.0.1:7087 - "GET /_app/immutable/chunks/singletons.c09a1307.js HTTP/1.1" 304
2024-11-20 12:14:49,676 - INFO - 127.0.0.1:7090 - "GET /_app/immutable/chunks/index.5c08976b.js HTTP/1.1" 304
2024-11-20 12:14:49,677 - INFO - 127.0.0.1:7091 - "GET /_app/immutable/entry/app.3dfd6829.js HTTP/1.1" 304
2024-11-20 12:14:49,679 - INFO - 127.0.0.1:7092 - "GET /_app/immutable/chunks/index.60ee613b.js HTTP/1.1" 304
2024-11-20 12:14:49,712 - INFO - 127.0.0.1:7092 - "GET /favicon.png HTTP/1.1" 200
2024-11-20 12:14:51,036 - INFO - 127.0.0.1:7092 - "GET / HTTP/1.1" 200
```
刷新了非常多，web界面进去啥也没有，重启后serve信息如下：
```
Database initialized successfully at C:\Users\Administrator\.memos\database.db
2024-11-20 12:16:22,304 - INFO - Database path: C:\Users\Administrator\.memos\database.db
2024-11-20 12:16:22,304 - INFO - VLM plugin enabled: modelname='minicpm-v' endpoint='http://localhost:11434' token='' concurrency=8 force_jpeg=True prompt='请帮描述这个图片中的内容，包括画面格局、出现的视觉元素等'
2024-11-20 12:16:22,304 - INFO - OCR plugin enabled: endpoint='http://localhost:5555/predict' token='' concurrency=8 use_local=True force_jpeg=False
2024-11-20 12:16:22,305 - INFO - VLM plugin initialized
2024-11-20 12:16:22,305 - INFO - Model Name: minicpm-v
2024-11-20 12:16:22,305 - INFO - Endpoint: http://localhost:11434
2024-11-20 12:16:22,305 - INFO - Token: 
2024-11-20 12:16:22,305 - INFO - Concurrency: 8
2024-11-20 12:16:22,305 - INFO - Force JPEG: True
2024-11-20 12:16:22,305 - INFO - Prompt: 请帮描述这个图片中的内容，包括画面格局、出现的视觉元素等
2024-11-20 12:16:25,678 - INFO - OCR plugin initialized
2024-11-20 12:16:25,678 - INFO - Endpoint: http://localhost:5555/predict
2024-11-20 12:16:25,678 - INFO - Token: 
2024-11-20 12:16:25,678 - INFO - Concurrency: 8
2024-11-20 12:16:25,678 - INFO - Use local: True
2024-11-20 12:16:27,694 - INFO - OCR library: rapidocr_openvino
2024-11-20 12:16:27,725 - INFO - Started server process [17232]
2024-11-20 12:16:27,725 - INFO - Waiting for application startup.
2024-11-20 12:16:27,725 - INFO - Application startup complete.
2024-11-20 12:16:27,726 - INFO - Uvicorn running on http://0.0.0.0:23323 (Press CTRL+C to quit)
2024-11-20 12:16:28,856 - INFO - 127.0.0.1:7379 - "GET / HTTP/1.1" 200
2024-11-20 12:16:30,461 - INFO - 127.0.0.1:7379 - "GET / HTTP/1.1" 200
2024-11-20 12:16:31,299 - INFO - 127.0.0.1:7379 - "GET / HTTP/1.1" 200
```

**Comment by arkohut** [comment]
请再提供下 `memos config` 的输出吧

**Comment by taliove** [comment]
<img width="684" alt="image" src="https://github.com/user-attachments/assets/29c046ed-6c6f-4924-a0bb-b78829476878">
一样遇到这个问题。在macOS上。
我改了端口也不行。
配置均为默认下。

**Comment by arkohut** [comment]
> <img alt="image" width="684" src="https://private-user-images.githubusercontent.com/4556014/387942621-29c046ed-6c6f-4924-a0bb-b78829476878.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwODA1NDQsIm5iZiI6MTczMjA4MDI0NCwicGF0aCI6Ii80NTU2MDE0LzM4Nzk0MjYyMS0yOWMwNDZlZC02YzZmLTQ5MjQtYTBiYi1iNzg4Mjk0NzY4NzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMDUyNDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzQ3MzhkZjViYmJkOTJmNDQ1YWVmNjZkOTBiMGUwZDUxNGEyNDQwOGFiYjU0ZTMyZGFmMjZmNTA5M2IxMDdkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0pIqLcdHyWTbEDAPfnpzKrb4hGdlZ6AeEiA3s8-WUsQ"> 一样遇到这个问题。在macOS上。 我改了端口也不行。 配置均为默认下。

你好，感谢尝试这个项目。看起来是没有成功下载模型导致的，这里麻烦将 `~/.memos/config.yaml` 中 `embedding.use_modelscope` 设置为 `true` 并重启一下试试看

**Comment by yuyun2000** [comment]
config如下：
```
base_dir: ~/.memos
database_path: database.db
default_library: screenshots
screenshots_dir: screenshots

server_host: 0.0.0.0
server_port: 23323

# Enable authentication by uncommenting the following lines
# auth_username: admin
# auth_password: admin

default_plugins:
- builtin_ocr
# - builtin_vlm

# using ollama as the vlm server
# vlm:
#   concurrency: 8
#   endpoint: http://localhost:11434
#   force_jpeg: true
#   modelname: minicpm-v
#   prompt: 请帮描述这个图片中的内容，包括画面格局、出现的视觉元素等
#   token: ''

# using local ocr
ocr:
  concurrency: 8
  # this is not used if use_local is true
  endpoint: http://localhost:5555/predict
  force_jpeg: false
  token: ''
  use_local: true
  use_modelscope: true

# using local embedding
embedding:
  # this is not used if use_local is true
  endpoint: http://localhost:11434/api/embed
  model: jinaai/jina-embeddings-v2-base-zh
  num_dim: 768
  use_local: true
  use_modelscope: true

# using ollama embedding
# embedding:
#   endpoint: http://localhost:11434/api/embed # this is not used
#   model: arkohut/gte-qwen2-1.5b-instruct:q8_0
#   num_dim: 1536
#   use_local: false
#   use_modelscope: false

record_interval: 4 # seconds
```
你看我已经关掉了vlm，但是上面的log信息还是开了vlm

**Comment by taliove** [comment]
> > <img alt="image" width="684" src="https://private-user-images.githubusercontent.com/4556014/387942621-29c046ed-6c6f-4924-a0bb-b78829476878.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwODA1NDQsIm5iZiI6MTczMjA4MDI0NCwicGF0aCI6Ii80NTU2MDE0LzM4Nzk0MjYyMS0yOWMwNDZlZC02YzZmLTQ5MjQtYTBiYi1iNzg4Mjk0NzY4NzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMDUyNDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzQ3MzhkZjViYmJkOTJmNDQ1YWVmNjZkOTBiMGUwZDUxNGEyNDQwOGFiYjU0ZTMyZGFmMjZmNTA5M2IxMDdkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0pIqLcdHyWTbEDAPfnpzKrb4hGdlZ6AeEiA3s8-WUsQ"> 一样遇到这个问题。在macOS上。 我改了端口也不行。 配置均为默认下。
> 
> 你好，感谢尝试这个项目。看起来是没有成功下载模型导致的，这里麻烦将 `~/.memos/config.yaml` 中 `embedding.use_modelscope` 设置为 `true` 并重启一下试试看

谢谢回复。改了后，仍然有问题。
我的配置如下：

```yaml
base_dir: ~/.memos
database_path: database.db
default_library: screenshots
screenshots_dir: screenshots

server_host: 0.0.0.0
server_port: 28839

# Enable authentication by uncommenting the following lines
# auth_username: admin
# auth_password: changeme

default_plugins:
- builtin_ocr
# - builtin_vlm

# using ollama as the vlm server
vlm:
  concurrency: 8
  endpoint: http://localhost:11434
  force_jpeg: true
  modelname: minicpm-v
  prompt: 请帮描述这个图片中的内容，包括画面格局、出现的视觉元素等
  token: ''

# using local ocr
ocr:
  concurrency: 8
  # this is not used if use_local is true
  endpoint: http://localhost:5555/predict
  force_jpeg: false
  token: ''
  use_local: true

# using local embedding
embedding:
  # this is not used if use_local is true
  endpoint: http://localhost:11434/api/embed
  model: arkohut/jina-embeddings-v2-base-zh
  num_dim: 768
  use_local: true
  use_modelscope: false

# using ollama embedding
# embedding:
#   endpoint: http://localhost:11434/api/embed # this is not used
#   model: arkohut/gte-qwen2-1.5b-instruct:q8_0
#   num_dim: 1536
#   use_local: false
#   use_modelscope: false

record_interval: 4 # seconds
```

**Comment by yuyun2000** [comment]
![image](https://github.com/user-attachments/assets/de766ce6-040c-49cb-90f8-ffed2c5c2c64)
改成原始端口后，并且使用其他浏览器依然访问不了，而且都是只加载了图标，页面一片空白

**Comment by noonisy** [comment]
你可以使用`memos ps`，看看当前已经启动的服务（正常是三个都启动，serve record watch）。同时，发现如果开着代理，可能会影响`watch`命令运行，同样报错`Failed to retrieve libraries: 502 - `

**Comment by yuyun2000** [comment]
代理关掉后，watch依然启动不了：
```
$ memos ps
Name    Status       PID    Started At           Running For
serve   Running      5364   2024-11-20 13:56:52  0:00:10
watch   Not Running  -      -                    -
record  Running      30640  2024-11-20 13:56:52  0:00:10
```

**Comment by noonisy** [comment]
在`launch.bat`中设置了，`timeout /t 15 /nobreak >nul`，`watch`需要15秒后执行
![Snipaste_2024-11-20_14-00-54](https://github.com/user-attachments/assets/47309e80-c1bc-4ac0-a556-98df5476101a)

**Comment by yuyun2000** [comment]
完全关闭代理后，三个进程都正常运行：
```
memos ps
Name    Status      PID  Started At           Running For
serve   Running   25272  2024-11-20 14:02:01  0:02:20
watch   Running   27932  2024-11-20 14:02:16  0:02:05
record  Running   29368  2024-11-20 14:02:01  0:02:20
```
但是有个问题，我依然进不去ui界面

**Comment by arkohut** [comment]
> 完全关闭代理后，三个进程都正常运行：
> 
> ```
> memos ps
> Name    Status      PID  Started At           Running For
> serve   Running   25272  2024-11-20 14:02:01  0:02:20
> watch   Running   27932  2024-11-20 14:02:16  0:02:05
> record  Running   29368  2024-11-20 14:02:01  0:02:20
> ```
> 
> 但是有个问题，我依然进不去ui界面
> 
> serve日志下有很多404：
> 
> ```
> 2024-11-20 14:06:35,180 - INFO - 127.0.0.1:14507 - "POST /libraries/1/entities?trigger_webhooks_flag=false&update_index=true HTTP/1.1" 200
> 2024-11-20 14:06:38,848 - INFO - 127.0.0.1:14509 - "GET /libraries/1 HTTP/1.1" 200
> 2024-11-20 14:06:39,476 - INFO - 127.0.0.1:14511 - "GET /libraries/1/entities/by-filepath?filepath=C%3A%5CUsers%5CAdministrator%5C.memos%5Cscreenshots%5C20241120%5Cscreenshot-20241120-140632-of-monitor_2.webp HTTP/1.1" 404
> 2024-11-20 14:06:40,120 - INFO - 127.0.0.1:14514 - "POST /libraries/1/entities?trigger_webhooks_flag=false&update_index=true HTTP/1.1" 200
> 2024-11-20 14:06:43,840 - INFO - 127.0.0.1:14517 - "GET /libraries/1 HTTP/1.1" 200
> 2024-11-20 14:06:44,484 - INFO - 127.0.0.1:14519 - "GET /libraries/1/entities/by-filepath?filepath=C%3A%5CUsers%5CAdministrator%5C.memos%5Cscreenshots%5C20241120%5Cscreenshot-20241120-140638-of-monitor_2.webp HTTP/1.1" 404
> 2024-11-20 14:06:45,201 - INFO - 127.0.0.1:14521 - "POST /libraries/1/entities?trigger_webhooks_flag=false&update_index=true HTTP/1.1" 200
> ```

这个 404 是正常的，就是先检查文件是否存在～从这个日志来看你的服务已经运行起来了的～

**Comment by yuyun2000** [comment]
文件都是有的，db也在增长，但是就是进不去webui...

**Comment by arkohut** [comment]
> 文件都是有的，db也在增长，但是就是进不去webui...
> 
> 这可咋办啊，这剩下临门一脚比跑了一半还难受啊

在命令行执行 `curl localhost:23323` 看看是否有返回。

如果确认有的话就换个浏览器试试看吧～

**Comment by noonisy** [comment]
F12看看控制台？试试访问`http://localhost:8839/search?q=`，应该返回当前所有data

**Comment by yuyun2000** [comment]
控制台输出如下：
```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.Understand this errorAI
scheduler.5c1cff6e.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.Understand this errorAI
singletons.c09a1307.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.Understand this errorAI
index.5c08976b.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.Understand this errorAI
app.3dfd6829.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.Understand this errorAI
index.60ee613b.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.Understand this errorAI
localhost/:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost:8839/_app/immutable/entry/start.4362bce6.js
```
我用火狐，edge 或者手机的safari都不行啊

**Comment by noonisy** [comment]
实在不行就pip uninstall memos，重新装一遍，目前版本0.19.1

**Comment by yuyun2000** [comment]
已经卸载，然后删除所有文件，重装，问题依旧啊

**Comment by noonisy** [comment]
现在输出啥

**Comment by yuyun2000** [comment]
![image](https://github.com/user-attachments/assets/c11fb2ab-a7d8-4f21-8f23-05262f39cfb6)
问题y依旧，我用火狐浏览器调试，输出的这个信息可能有用点

**Comment by noonisy** [comment]
手动给环境中`memos`库中的`static/app.html`中的`link`加上`type="application/javascript"`看看？

**Comment by arkohut** [comment]
> ![image](https://private-user-images.githubusercontent.com/72307249/387979515-c11fb2ab-a7d8-4f21-8f23-05262f39cfb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwODY4MTUsIm5iZiI6MTczMjA4NjUxNSwicGF0aCI6Ii83MjMwNzI0OS8zODc5Nzk1MTUtYzExZmIyYWItYTdkOC00ZjIxLThmMjMtMDUyNjJmMzljZmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDA3MDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhYmEwOTJkM2NiN2M5YmYxZTFiOTRiZmRjM2Y1MDFjMDM1N2Y2NWI5YmExNTViY2QzZjg4Nzc5ZGU3NmE5MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nEDK3GYkLnHeH-16ikcPPgQotgUYzWzItvx2sLbLv3U) 问题y依旧，我用火狐浏览器调试，输出的这个信息可能有用点

我感觉应该是 fastapi 返回的文件的 content type 出了问题，可否尝试更新：

```
pip install -U fastapi
```

**Comment by yuyun2000** [comment]
fastapi已经是最新的了 0.115.5  尝试了0.114.0和0.111.0 均不行...

**Comment by yuyun2000** [comment]
那个app.html 我直接用浏览器打开也看不了啊

**Comment by arkohut** [comment]
> > ![image](https://private-user-images.githubusercontent.com/72307249/387979515-c11fb2ab-a7d8-4f21-8f23-05262f39cfb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwODY4MTUsIm5iZiI6MTczMjA4NjUxNSwicGF0aCI6Ii83MjMwNzI0OS8zODc5Nzk1MTUtYzExZmIyYWItYTdkOC00ZjIxLThmMjMtMDUyNjJmMzljZmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDA3MDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhYmEwOTJkM2NiN2M5YmYxZTFiOTRiZmRjM2Y1MDFjMDM1N2Y2NWI5YmExNTViY2QzZjg4Nzc5ZGU3NmE5MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nEDK3GYkLnHeH-16ikcPPgQotgUYzWzItvx2sLbLv3U) 问题y依旧，我用火狐浏览器调试，输出的这个信息可能有用点
> 
> 我感觉应该是 fastapi 返回的文件的 content type 出了问题，可否尝试更新：
> 
> ```
> pip install -U fastapi
> ```

针对这个报错，它是说本来应该 text/javascript 的 content type 却返回了 text/plain ，结果 js 就没有执行。但是这个问题我的确没有遇到。不过也可能是和 windows 有关系的，我目前并没有在 windows 测试这个问题。

**Comment by yuyun2000** [comment]
那咋办 作者大人

**Comment by arkohut** [comment]
我测试了 windows 是好的...然后麻烦再确认下 `starlette` 的版本。

**Comment by yuyun2000** [comment]
0.37.2

**Comment by yuyun2000** [comment]
一天过去了，我还在孤独的等待

**Comment by taliove** [comment]
> 一天过去了，我还在孤独的等待 @arkohut

我卸载memos后，重新安装到最新版本后解决我的问题了。可以打开管理页面了。

**Comment by arkohut** [comment]
> > 一天过去了，我还在孤独的等待 @arkohut
> 
> 我卸载memos后，重新安装到最新版本后解决我的问题了。可以打开管理页面了。

你的问题和他的不是一个额，你的是依赖问题，最新的版本已经解决了

**Comment by arkohut** [comment]
> 一天过去了，我还在孤独的等待 @arkohut

因为这个问题我目前没有复现啊，你要不也试试重装啊

**Comment by arkohut** [comment]
可否执行这个命令返回给我：

```sh
python -c "import mimetypes; print (mimetypes.guess_type('_app/immutable/entry/app.ae4ec061.js'))"
```

**Comment by yuyun2000** [comment]
已经更新memos==21.2，并且清空cache重新运行，依旧无法访问网页，上面命令输出：
```
$ python -c "import mimetypes; print (mimetypes.guess_type('_app/immutable/entry/app.ae4ec061.js'))"
('text/plain', None)
```
@arkohut

**Comment by arkohut** [comment]
更新了版本，`0.21.3` 麻烦尝试一下

**Comment by yuyun2000** [comment]
已经正常显示！！

**Comment by arkohut** [comment]
没想到 windows 这么多坑啊 😢

**Comment by yuyun2000** [comment]
辛苦了，感觉是不是可以加个resize，把照片都保存到1080p节省空间，我这俩4k的屏幕长时间搞下去害怕啊
