### ISSUE TITLE
how to change the config file to support openai model?

### ISSUE THREAD

**Issue by HeMuling** [arkohut/pensieve#9]
I've noticed that in readme you said "Compatible with any OpenAI API models", is there any guide for that?

**Comment by arkohut** [comment]
If you are using OpenAI as the vlm model provider. You can follow the instruction in https://github.com/arkohut/pensieve?tab=readme-ov-file#using-ollama-for-visual-search . And change vlm config part in `~/.memos/config.yml` like this:

```yaml
vlm:
  endpoint: https://api.openai.com
  modelname: <openai model name>
  force_jpeg: true
  prompt: Please describe the content of this image, including the layout and visual elements  # Prompt sent to the model
  token: <openai api key>
```

Please follow the full part in the doc to enable vlm plugin.

**Comment by HeMuling** [comment]
thanks, can I use openai for embedding?

I tried:
```
embedding:
  enable: true
  endpoint: https://api.openai.com/v1/embeddings
  model: text-embedding-3-small
  num_dim: 1536
  use_local: false
  use_modelscope: false
  token: 'my-openai-api-key'
```

and when I tried `memos scan`, I get
```
2024-11-19 15:18:55,773 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/memos/server.py", line 347, in update_entity
    crud.update_entity_index(entity, db)
  File "/opt/homebrew/lib/python3.11/site-packages/memos/crud.py", line 755, in update_entity_index
    embeddings = get_embeddings([vec_metadata])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/memos/embedding.py", line 65, in get_embeddings
    embeddings = get_remote_embeddings(texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/memos/embedding.py", line 80, in get_remote_embeddings
    response.raise_for_status()
  File "/opt/homebrew/lib/python3.11/site-packages/httpx/_models.py", line 758, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://api.openai.com/v1/embeddings'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401
```

**Comment by arkohut** [comment]
> Sorry, right now it is not supported. I support the batch embed api from ollama...

But I will add this feature to make the full OpenAI API compatible.

**Comment by arkohut** [comment]
https://github.com/arkohut/pensieve/pull/31 This is done.
